name: "Labeler: Download Issues"

on:
  workflow_call:
    inputs:
      github_token:
        description: "The GitHub token (defaults to action token)"
        type: string
      org_repo:
        description: "The org/repo to download data from (defaults to current repository)"
        type: string
      label_prefix:
        description: "Label prefix"
        type: string
        default: "area-"
      page_limit:
        description: "Max pages of items to download (100 items per page)"
        type: number
        default: 500
        required: true
      retries:
        description: "Comma-separated list of retry delays in seconds"
        type: string
        default: "30,30,30,300,300,3600"

  workflow_dispatch:
    inputs:
      github_token:
        description: "The GitHub token (defaults to action token)"
        type: string
      org_repo:
        description: "The org/repo to download data from (defaults to current repository)"
        type: string
      label_prefix:
        description: "Label prefix"
        type: string
        default: "area-"
      page_limit:
        description: "Max pages of items to download (100 items per page)"
        type: number
        default: 500
        required: true
      retries:
        description: "Comma-separated list of retry delays in seconds"
        type: string
        default: "30,30,30,300,300,3600"

permissions:
  issues: read

jobs:
  labeler-download-issues:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: "Check out the '${{ github.action_repository || github.repository }}' repo"
        uses: actions/checkout@v4
        with:
          repository: ${{ github.action_repository || github.repository }}

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: "Run GitHubDownloader"
        run: |
          dotnet run --project src/GitHubDownloader -- \
            --token "${{ inputs.github_token || secrets.GITHUB_TOKEN }}" \
            --repo "${{ inputs.org_repo || github.repository }}" \
            --issue-data labeler-cache/issue-data.tsv \
            --retries "${{ inputs.retries || '30,30,30,300,300,3600' }}" \
            --label-prefix "${{ inputs.label_prefix || 'area-' }}" \
            --page-limit ${{ fromJSON( inputs.page_limit || 500 ) }}

      - name: "Cache issue-data.tsv into 'github-ml-labeler/${{ inputs.org_repo || github.repository }}/download-issues'"
        uses: actions/cache@v4
        with:
          path: labeler-cache/issue-data.tsv
          key: github-ml-labeler/${{ inputs.org_repo || github.repository }}/download-issues
