name: "Labeler: Label Issue"

on:
  issues:
    types: [opened, edited, transferred, unlabeled]

  workflow_call:
    inputs:
      number:
        description: "Issue Number"
        type: number
        required: true
      label_prefix:
        description: "Label Prefix"
        type: string
        required: true
      threshold:
        description: "The minimum confidence score for a label prediction"
        type: number
        default: 0.75
        required: true
      default_label:
        description: "Default Label (leave blank for no default label)"
        type: string
      model_repo:
        description: "The org/repo to use for the cached model (defaults to current repository)"
        type: string

  workflow_dispatch:
    inputs:
      github_token:
        description: "The GitHub token (defaults to action token)"
        type: string
      org_repo:
        description: "The org/repo to use (defaults to current repository)"
        type: string
      number:
        description: "Issue Number"
        type: number
        required: true
      label_prefix:
        description: "Label Prefix"
        default: "area-"
        required: true
      threshold:
        description: "The minimum confidence score for a label prediction"
        type: number
        default: 0.75
        required: true
      default_label:
        description: "Default Label (leave blank for no default label)"
        default: "needs-area-label"
      model_repo:
        description: "The org/repo to use for the cached model (defaults to current repository)"
        type: string

permissions:
  issues: write

jobs:
  label-issue:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: "Check out the 'jeffhandley/github-ml-labeler' repo"
        uses: actions/checkout@v4
        with:
          repository: jeffhandley/github-ml-labeler

      # Restore cache after checkout to ensure files aren't cleaned or removed
      - name: "Restore issue-model.zip from 'github-ml-labeler/${{ inputs.model_repo || github.repository }}/model-issues'"
        id: restore-cache
        uses: actions/cache@v4
        with:
          path: labeler-cache/issue-model.zip
          key: github-ml-labeler/${{ inputs.model_repo || github.repository }}/model-issues
          fail-on-cache-miss: true

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: "Run LabelPredictor"
        run: |
          dotnet run --project src/LabelPredictor -- \
            --token "${{ inputs.github_token || secrets.GITHUB_TOKEN }}" \
            --repo "${{ inputs.org_repo || github.repository }}" \
            --issue-model labeler-cache/issue-model.zip \
            --issue ${{ fromJSON(inputs.number || github.event.issue.number) }} \
            --label-prefix "${{ inputs.label_prefix || 'area-' }}" \
            --threshold ${{ fromJSON( inputs.threshold || 0.75 ) }} \
            --default-label "${{ inputs.default_label || 'needs-area-label' }}"
