name: "Labeler: Download Issues"

on:
  schedule:
    - cron: "12 1 * * 1"

  workflow_dispatch:
    inputs:
      org_repo:
        description: "The org/repo to use (defaults to current repo)"
        type: string
      github_token:
        description: "The GitHub token (defaults to current repo's token)"
        type: string
      label_prefix:
        description: "Label prefix"
        type: string
        default: "area-"
        required: true
      page_limit:
        description: "Max pages of issues to download (100 issues per page)"
        type: number
        default: 500
        required: true

permissions:
  issues: read

jobs:
  labeler-download-issues:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: "Run GitHubDownloader"
        run: |
          dotnet run --project src/GitHubDownloader -- \
            "${{ inputs.org_repo || $GITHUB_REPOSITORY }}" \
            "${{ inputs.github_token || secrets.GITHUB_TOKEN }}" \
            --issue-data labeler-cache/issue-data.tsv \
            --retries "30,30,30,300,300,3600" \
            --label-prefix "${{ inputs.label_prefix || 'area-' }}" \
            --page-limit ${{ fromJSON( inputs.page_limit || 500 ) }}

      - name: "Cache issue-data.tsv"
        uses: actions/cache@v4
        with:
          path: labeler-cache/issue-data.tsv
          key: github-ml-labeler/${{ inputs.org_repo || $GITHUB_REPOSITORY }}/download-issues
