name: "Labeler: Promote Pull Model"

on:
  workflow_call:
    inputs:
      model_cache_key:
        description: "The cache key suffix to promote"
        type: string
        required: true

  workflow_dispatch:
    inputs:
      model_cache_key:
        description: "The cache key suffix to promote"
        type: string
        required: true

env:
  MODEL_PATH: labeler-cache/pull-model.zip
  MODEL_CACHE_KEY: github-ml-labeler/pulls/model/${{ inputs.model_cache_key }}
  PROMOTION_CACHE_KEY: github-ml-labeler/pulls/model/${{ github.repository }}
  BACKUP_CACHE_KEY: github-ml-labeler/pulls/model/${{ github.repository }}/backup
  GH_TOKEN: ${{ github.token }}

permissions:
  actions: write

jobs:
  promote-pull-model:
    runs-on: ubuntu-latest

    steps:
      - name: "Check for existing backup cache entry"
        id: check-backup
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.MODEL_PATH }}
          key: ${{ env.BACKUP_CACHE_KEY }}
          fail-on-cache-miss: false

      - name: "Delete existing backup cache entry"
        if: steps.check-backup.outputs.cache-hit == 'true'
        run: |
            gh api --method DELETE \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              /repos/${{ github.repository }}/actions/caches?key=${{ env.BACKUP_CACHE_KEY }}

            rm ${{ env.MODEL_PATH }}

      - name: "Check for existing promotion cache entry"
        id: check-promotion
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.MODEL_PATH }}
          key: ${{ env.PROMOTION_CACHE_KEY }}
          fail-on-cache-miss: false

      - name: "Cache backup of existing promotion model"
        if: steps.check-promotion.outputs.cache-hit == 'true'
        id: backup-model
        uses: actions/cache/save@v4
        with:
          path: ${{ env.MODEL_PATH }}
          key: ${{ env.BACKUP_CACHE_KEY }}

      - name: "Delete existing cache entry"
        if: steps.check-promotion.outputs.cache-hit == 'true'
        run: |
            gh api --method DELETE \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              /repos/${{ github.repository }}/actions/caches?key=${{ env.PROMOTION_CACHE_KEY }}

            rm ${{ env.MODEL_PATH }}

      - name: "Restore model from cache"
        id: restore-cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.MODEL_PATH }}
          key: ${{ env.MODEL_CACHE_KEY }}
          fail-on-cache-miss: true

      - name: "Save model to cache"
        uses: actions/cache/save@v4
        with:
          path: ${{ env.MODEL_PATH }}
          key: ${{ env.PROMOTION_CACHE_KEY }}
