name: "Labeler: Model Pulls"

on:
  schedule:
    - cron: "34 4 * * 4"

  workflow_dispatch:

jobs:
  model-pulls:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore cache
        id: restore-cache
        uses: actions/cache@v4
        with:
          path: labeler-cache/pull-data.tsv
          key: github-ml-labeler/download-pulls
          fail-on-cache-miss: true

      - name: Run ModelCreator
        run: |
          cat labeler-cache/pull-data.tsv
          cd src/ModelCreator
          dotnet run -- --pull-data ../../labeler-cache/pull-data.tsv --pull-model ../labeler-cache/pull-model.zip

      - name: Save model to cache
        uses: actions/cache@v4
        with:
          path: labeler-cache/pull-model.zip
          key: github-ml-labeler/model-pulls
