name: "Labeler: Model Pull Requests"

on:
  workflow_call:
    inputs:
      data_repo:
        description: "The org/repo to load pull request data from (defaults to current repository)"
        type: string
      data_key:
        description: "The optional key to use in the cache key suffix for loading the downloaded data"
        type: string
      model_repo:
        description: "The org/repo to cache the pull request model for (defaults to current repository)"
        type: string
      model_key:
        description: "The optional key to use in the cache key suffix for saving the model"
        type: string

  workflow_dispatch:
    inputs:
      data_repo:
        description: "The org/repo to load pull request data from (defaults to current repository)"
        type: string
      data_key:
        description: "The optional key to use in the cache key suffix for loading the downloaded data"
        type: string
      model_repo:
        description: "The org/repo to cache the pull request model for (defaults to current repository)"
        type: string
      model_key:
        description: "The optional key to use in the cache key suffix for saving the model"
        type: string

jobs:
  model-pulls:
    runs-on: ubuntu-latest
    timeout-minutes: 600

    steps:
      - name: "Check out the 'jeffhandley/github-ml-labeler' repo"
        uses: actions/checkout@v4
        with:
          repository: jeffhandley/github-ml-labeler

      # Restore cache after checkout to ensure files aren't cleaned or removed
      - name: "Restore pull-data.tsv from 'github-ml-labeler/${{ inputs.data_repo || github.repository }}/download-pulls/${{ inputs.data_key }}'"
        id: restore-cache
        uses: actions/cache@v4
        with:
          path: labeler-cache/pull-data.tsv
          key: github-ml-labeler/${{ inputs.data_repo || github.repository }}/download-pulls/${{ inputs.data_key }}
          fail-on-cache-miss: true

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: "Run ModelCreator"
        run: |
          dotnet run --project src/ModelCreator -- \
            --pull-data labeler-cache/pull-data.tsv \
            --pull-model labeler-cache/pull-model.zip

      - name: "Cache pull-model.zip into 'github-ml-labeler/${{ inputs.model_repo || github.repository }}/model-pulls/${{ inputs.model_key }}'"
        uses: actions/cache@v4
        with:
          path: labeler-cache/pull-model.zip
          key: github-ml-labeler/${{ inputs.model_repo || github.repository }}/model-pulls/${{ inputs.model_key }}
